version: "2"
services:
  redis:
    image: redis:3.2
    logging:
      driver: "none"
  web:
    environment:
      # Pickup the AWS secret and access key from host env
      - TAAR_MAX_RESULTS=4
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - CACHE_URL
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      "web-dev"
    links:
      - redis
