# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_EMAIL   - login info for docker hub
# DOCKER_USER
# DOCKER_PASS
#

version: 2
jobs:
  build:
    machine:
      enable: true
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./bin/build
  deploy:
    machine:
      enable: true
      docker_layer_caching: true
    steps:
      - run: ./bin/deploy
  integration_test:
    machine:
      enable: true
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: ./bin/test

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - integration_test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - integration_test
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only: master
